### PR TITLE
Fix dpctl.lsplatform() to output in jupyter notebook

### LINKED ISSUE #796: dpctl.lsplatform() does not output in jupyter notebook
`dpctl.lsplatform()` produces an intended output when called in a terminal, but produces no output when called from jupyter notebook.

At the same time `dev.print_device_info()` works fine from both. 

The issue is for `lsplatform` to also work from jupyter notebook.

### PR DESCRIPTION
**Pull request by vlad-perevezentsev**
Closes #796 

This PR changes `DPCTLPlatformMgr_PrintInfo` function to return `char *` instead of outputting it in `libsyclinterface` , and use that to print using CPython.

### CODE REVIEW

**Review by oleksandr-pavlyk — CHANGES_REQUESTED** [review]
Please do not change the API public functions. Instead extend the API and change the implementation of the API. 

`DPCTLPlatformMgr_PrintInfo` calls internal routine to get `std::string` and outputs it as before. 
`DPCTLPlatformMgr_GetInfo` calls internal routine to get `std::string` and copies the result into C-style string.

**Comment by oleksandr-pavlyk** [comment]
@vlad-perevezentsev Thank you for making the requested changes. DPCTLSyclInterface tests for `DPCTLPlatformMgr_GetInfo` are also needed. 

The test would call a function and check that the returned `const char *` is not a nullptr.

File: libsyclinterface/tests/test_sycl_platform_interface.cpp [hunk 1]
```diff
@@ -224,6 +224,14 @@ TEST_P(TestDPCTLSyclPlatformInterface, ChkCopyNullArg)
     EXPECT_NO_FATAL_FAILURE(DPCTLPlatform_Delete(Copied_PRef));
 }
 
+TEST_P(TestDPCTLSyclPlatformInterface, ChkGetInfo)
+{
+    const char *info_str = nullptr;
+    EXPECT_NO_FATAL_FAILURE(info_str = DPCTLPlatformMgr_GetInfo(PRef,0);
```
Comment (oleksandr-pavlyk) [inline libsyclinterface/tests/test_sycl_platform_interface.cpp:230]:
```suggestion
    EXPECT_NO_FATAL_FAILURE(info_str = DPCTLPlatformMgr_GetInfo(PRef,0));
```

File: libsyclinterface/tests/test_sycl_platform_interface.cpp [hunk 2]
```diff
@@ -255,6 +263,38 @@ TEST_F(TestDPCTLSyclDefaultPlatform, ChkGetBackend)
     check_platform_backend(PRef);
 }
 
+TEST_P(TestDPCTLSyclDefaultPlatform, ChkGetInfo0)
+{
+    const char *info_str = nullptr;
+    EXPECT_NO_FATAL_FAILURE(info_str = DPCTLPlatformMgr_GetInfo(PRef,0);
```
Comment (oleksandr-pavlyk) [inline libsyclinterface/tests/test_sycl_platform_interface.cpp:269]:
```suggestion
    EXPECT_NO_FATAL_FAILURE(info_str = DPCTLPlatformMgr_GetInfo(PRef,0));
```

File: libsyclinterface/tests/test_sycl_platform_interface.cpp [hunk 3]
```diff
@@ -255,6 +263,38 @@ TEST_F(TestDPCTLSyclDefaultPlatform, ChkGetBackend)
...
+    ASSERT_TRUE(info_str != nullptr);
+    EXPECT_NO_FATAL_FAILURE(DPCTLCString_Delete(info_str));
+}
+
+TEST_P(TestDPCTLSyclDefaultPlatform, ChkGetInfo1)
+{
+    const char *info_str = nullptr;
+    EXPECT_NO_FATAL_FAILURE(info_str = DPCTLPlatformMgr_GetInfo(PRef,1);
```
Comment (oleksandr-pavlyk) [inline libsyclinterface/tests/test_sycl_platform_interface.cpp:277]:
```suggestion
    EXPECT_NO_FATAL_FAILURE(info_str = DPCTLPlatformMgr_GetInfo(PRef,1));
```

File: libsyclinterface/tests/test_sycl_platform_interface.cpp [hunk 4]
```diff
@@ -255,6 +263,38 @@ TEST_F(TestDPCTLSyclDefaultPlatform, ChkGetBackend)
...
+    ASSERT_TRUE(info_str != nullptr);
+    EXPECT_NO_FATAL_FAILURE(DPCTLCString_Delete(info_str));
+}
+
+TEST_P(TestDPCTLSyclDefaultPlatform, ChkGetInfo2)
+{
+    const char *info_str = nullptr;
+    EXPECT_NO_FATAL_FAILURE(info_str = DPCTLPlatformMgr_GetInfo(PRef,2);
```
Comment (oleksandr-pavlyk) [inline libsyclinterface/tests/test_sycl_platform_interface.cpp:285]:
```suggestion
    EXPECT_NO_FATAL_FAILURE(info_str = DPCTLPlatformMgr_GetInfo(PRef,2));
```

File: libsyclinterface/tests/test_sycl_platform_interface.cpp [hunk 5]
```diff
@@ -255,6 +263,38 @@ TEST_F(TestDPCTLSyclDefaultPlatform, ChkGetBackend)
...
+    ASSERT_TRUE(info_str != nullptr);
+    EXPECT_NO_FATAL_FAILURE(DPCTLCString_Delete(info_str));
+}
+
+TEST_P(TestDPCTLSyclDefaultPlatform, ChkGetInfo3)
+{
+    const char *info_str = nullptr;
+    EXPECT_NO_FATAL_FAILURE(info_str = DPCTLPlatformMgr_GetInfo(PRef,3);
```
Comment (oleksandr-pavlyk) [inline libsyclinterface/tests/test_sycl_platform_interface.cpp:293]:
```suggestion
    EXPECT_NO_FATAL_FAILURE(info_str = DPCTLPlatformMgr_GetInfo(PRef,3));
```

**Review by oleksandr-pavlyk — APPROVED** [review]
I was able to build the coverage workflow manually. I was also able to manually confirm that the original issue of output of `dpctl.lsplatform()` not showing in remotely connected jupyter notebook has been fixed. 

LGTM! Waiting for the CI to run its course.

**Review by oleksandr-pavlyk — APPROVED** [review]

**Review by diptorupd — APPROVED** [review]
