### PR TITLE
Fixes incorrect output in dpctl.tensor.where strided implementation

### LINKED ISSUE #1170: dpct.tensor.where wrong results with different shapes
If shape of `condition` parameter is not equal to one of shapes of  `x` or `y` , dpctl.tensor.where returns an incorrect result.
For example
cond_shape = (4,) , x_shape = (4,), y_shape=(4,) - correct
cond_shape = (2, 3) , x_shape = (2, 3), y_shape=(3,) - correct 
cond_shape = (4,) , x_shape = (2, 3), y_shape=(2, 3) -  incorrect

```
#NUMPY
np_cond = [False, True, True, False]
np_x = np.ones((3,4))
np_y = np.zeros((3,4))

#DPT 
dpt_cond = dpt.asarray(np_cond)
dpt_x = dpt.asarray(np_x)
dpt_y = dpt.asarray(np_y)

np.where(np_cond, np_x, np_y)
>> array([[0., 1., 1., 0.],
          [0., 1., 1., 0.],
          [0., 1., 1., 0.]])

dpt.where(dpt_cond, dpt_x, dpt_y)
>> usm_ndarray([[0., 0., 0., 1.],
                [1., 1., 1., 1.],
                [1., 0., 0., 0.]], dtype=float32)

```

### PR DESCRIPTION
**Pull request by ndgrigorian**
This PR implements simplify_iteration_space_4 and indexers for offsets in 4 arrays to resolve #1170.
Additionally, implements contract_iter4 and simplifies calls to std::min in strided_iters.

The issue was caused by an oversight in the mapping of elements between arrays in the strided where kernel. As the destination array was not being simplified, there was not a guarantee that the nth element of the destination corresponded to the correct element in x1 or x2.

- [X] Have you provided a meaningful PR description?
- [X] Have you added a test, reproducer or referred to an issue with a reproducer?
- [X] Have you tested your changes locally for CPU and GPU devices?
- [X] Have you made sure that new changes do not introduce compiler warnings?
- [ ] Have you checked performance impact of proposed changes?
- [ ] If this PR is a work in progress, are you opening the PR as a draft?

### CODE REVIEW

**Comment by oleksandr-pavlyk** [comment]
I have added a test:

```python
def test_where_invariants():
    test_sh = (6, 8,)
    mask = dpt.asarray(np.random.choice([True, False], size=test_sh))
    p = dpt.ones(test_sh, dtype=dpt.int16)
    m = dpt.full(test_sh, -1, dtype=dpt.int16)
    inds_list = [(np.s_[:3], np.s_[::2],), (np.s_[::2], np.s_[::2],), (np.s_[::-1], np.s_[:],),]
    for ind in inds_list:
        r1 = dpt.where(mask, p, m)[ind]
        r2 = dpt.where(mask[ind], p[ind], m[ind])
        assert (dpt.asnumpy(r1) == dpt.asnumpy(r2)).all()
```

File: dpctl/tensor/libtensor/source/simplify_iteration_space.hpp [hunk 1]
```diff
@@ -87,6 +87,39 @@ void simplify_iteration_space_3(int &,
                                 py::ssize_t &,
                                 py::ssize_t &);
 
+void simplify_iteration_space_4(int &,
```
Comment (oleksandr-pavlyk) [inline dpctl/tensor/libtensor/source/simplify_iteration_space.hpp:90]: One day, it would be nice to figure out how to make this nicer, perhaps by packing data about `src1`, etc. into structs.

**Review by oleksandr-pavlyk — APPROVED** [review]

File: dpctl/tensor/libtensor/source/simplify_iteration_space.hpp (hunk 1 above)
Comment (oleksandr-pavlyk) [reply dpctl/tensor/libtensor/source/simplify_iteration_space.hpp:90]: And of course, this same comment applies to `simplify_iteration_space_3` and others.
